# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  workflow_dispatch:

env:
  NX_BRANCH: ${{ github.run_id }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  agents:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14.x
        uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          path: |
            '**/node_modules'
            !/node_modules/.cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - name: Start NX Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: |
            '**/node_modules'
            !/node_modules/.cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npx nx affected --base=main --target=build --parallel --max-parallel=3
      - run: npx nx affected --base=main --target=test --parallel --max-parallel=2
      - run: npx nx affected --base=main --target=lint --parallel --max-parallel=4
      - run: npx nx-cloud stop-all-agents
